baseURL = "https://marcusjacobson.github.io/techblog/"
languageCode = "en-us"
title = "Tech Blog by Marcus"
theme = "ananke"

sectionPagesMenu = "main"
enableRobotsTXT = true

[services.googleAnalytics]
id = ''

[pagination]
pagerSize = 3

[languages.en]
contentDir = "content/posts"
languageCode = 'en-US'
weight = 1
title = "Tech Blog by Marcus"

[sitemap]
changefreq = "monthly"
priority = 0.5
filename = "sitemap.xml"

[params]
text_color = ""
author = ""
favicon = ""
site_logo = ""
description = "The last theme you'll ever need. Maybe."
background_color_class = "bg-black"
featured_image_class = "cover bg-top"
cover_dimming_class = "bg-black-60"
recent_posts_number = 3
customCSS = ["css/custom.css"]

[params.ananke.social.share]
networks = [
  "email",
  "facebook",
  "bluesky",
  "linkedin"
]