baseURL = "https://marcusjacobson.github.io/techblog/"
languageCode = "en-us"
title = "Tech Portfolio - Marcus Jacobson"
theme = "ananke"

enableRobotsTXT = true

[services.googleAnalytics]
id = ''

[pagination]
pagerSize = 3

[languages.en]
languageCode = 'en-US'
weight = 1
title = "Tech Portfolio - Marcus Jacobson"

[sitemap]
changefreq = "monthly"
priority = 0.5
filename = "sitemap.xml"

[params]
text_color = ""
author = ""
favicon = ""
site_logo = ""
description = "The last theme you'll ever need. Maybe."
background_color_class = "bg-forest-green"
featured_image_class = "cover bg-top"
cover_dimming_class = "bg-black-60"
recent_posts_number = 3
customCSS = ["css/custom.css"]

[taxonomies]
  category = "categories"
  tag = "tags"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/posts/"
    weight = 2

  [[menu.main]]
    identifier = "profile"
    name = "Profile"
    url = "/profile/"
    weight = 3

# New parameters for different titles
top_header_title = "Home"
main_header_title = "Welcome to My Blog"
recent_posts_title = "Recent Posts"
header_title = "Tech Portfolio - Marcus Jacobson"

[params.ananke.social.share]
networks = [
  "email",
  "facebook",
  "bluesky",
  "linkedin"
]
